# Generated by Django 3.2.7 on 2021-09-29 23:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210929_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 23, 13, 12, 381826, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
